    FROM php:latest

    RUN mkdir C:\var\www\html

    COPY COPY C:\\Users\\fc\\Desktop\\webdeveloper\\webInstitucional\\personal

    EXPOSE 80

    CMD ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]