FROM php:latest

# Crea un directorio en el contenedor para almacenar la aplicación
RUN mkdir -p /var/www/html

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /var/www/html

# Copia los archivos de la aplicación al contenedor
COPY . /var/www/html

# Expone el puerto 80 para acceder a la aplicación
EXPOSE 80

# Define el comando de inicio para ejecutar la aplicación PHP
CMD ["php", "-S", "0.0.0.0:80"]